<a href="https://colab.research.google.com/github/LeeMinJun0102/itwill_middle_project/blob/main/%EB%B6%84%EC%84%9D(sklearn).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_validate
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import confusion_matrix, r2_score, f1_score
from sklearn.pipeline import Pipeline

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import AdaBoostClassifier

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import scipy

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# DataFrame rk 0, 1, 2 등급화

# 데이터 준비

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/중간 프로젝트/코랩으로 옮길 엑셀들/DF_final_final.xlsx')

## only you 홍천 데이터 준비

In [ ]:
gangwon = pd.read_excel('/content/drive/MyDrive/중간 프로젝트/코랩으로 옮길 엑셀들/for_hongchun.xlsx')

In [ ]:
hongchun = gangwon[gangwon['ADM_NM'] == '강원도홍천군']

In [ ]:
hongchun_grid = hongchun['grid_id'].values

In [ ]:
yes_hong_df = df[df['grid_id'].isin(hongchun_grid)]

## without you 홍천 데이터 준비

In [ ]:
no_hong_df = df[~df['grid_id'].isin(hongchun_grid)]

In [ ]:
no_hong_df

grid_id                                           geometry  rk_012  \
0      grid_25  POLYGON ((127.14503771433479 38.22783241130978...       0   
1      grid_26  POLYGON ((127.14503771433479 38.27783241130978...       0   
2      grid_55  POLYGON ((127.19503771433479 38.12783241130979...       0   
3      grid_56  POLYGON ((127.19503771433479 38.17783241130979...       0   
4      grid_57  POLYGON ((127.19503771433479 38.22783241130978...       0   
..         ...                                                ...     ...   
779  grid_1413  POLYGON ((129.34503771433504 37.22783241130984...       0   
780  grid_1414  POLYGON ((129.34503771433504 37.27783241130984...       1   
781  grid_1443  POLYGON ((129.39503771433505 37.12783241130984...       0   
782  grid_1444  POLYGON ((129.39503771433505 37.17783241130984...       0   
783  grid_1445  POLYGON ((129.39503771433505 37.22783241130984...       0   

     total_rk  national_highway_rk  national_rk  highway_rk  white_rk  \
0           0                    0            0           0         0   
1           0                    0            0           0         0   
2           0                    0            0           0         0   
3           0                    0            0           0         0   
4           0                    0            0           0         0   
..        ...                  ...          ...         ...       ...   
779         0                    0            0           0         0   
780         2                    0            0           0         2   
781         0                    0            0           0         0   
782         0                    0            0           0         0   
783         0                    0            0           0         0   

     wildlife_corridor  road_count  national_road_count local_road  \
0                    0           1                    1        463   
1                    0           0                    0          0   
2                    0           0                    0          0   
3                    0           0                    0          0   
4                    0           3                    3        463   
..                 ...         ...                  ...        ...   
779                  0           1                    1          0   
780                  0           1                    1          0   
781                  0           1                    1          0   
782                  0           0                    0          0   
783                  0           0                    0          0   

    national_highway highway  speed_limit  white_road_grade  dist_to_eco_m  \
0                  0       0           70                 1       0.000000   
1                  0       0            0                 0       0.000000   
2                  0       0            0                 1       0.000000   
3                  0       0            0                 1       0.000000   
4              3, 87       0           70                 2       0.000000   
..               ...     ...          ...               ...            ...   
779                7       0           70                 2       0.000000   
780                7       0           70                 2    8780.044607   
781                7       0           70                 3       0.000000   
782                0       0            0                 1       0.000000   
783                0       0            0                 1       0.000000   

     pig_count  rani_count  
0     1.540276    0.000000  
1     1.540276    0.000000  
2     1.540276    0.000000  
3     1.540276    0.000000  
4     1.540276    0.000000  
..         ...         ...  
779   0.000000    7.052573  
780   0.000000    7.052573  
781   0.000000    7.052573  
782   0.000000    7.052573  
783   0.000000    7.052573  

[675 rows x 19 columns]

# X, y, X_hong, y_hong

In [ ]:
X = no_hong_df[['wildlife_corridor', 'road_count', 'speed_limit', 'white_road_grade', 'pig_count', 'rani_count', 'dist_to_eco_m']].values
# X = no_hong_df[['wildlife_corridor', 'road_count', 'speed_limit', 'white_road_grade', 'pig_count', 'rani_count']].values
y = no_hong_df['rk_012'].values

In [ ]:
X_hong = yes_hong_df[['wildlife_corridor', 'road_count', 'speed_limit', 'white_road_grade', 'pig_count', 'rani_count', 'dist_to_eco_m']].values
# X_hong = yes_hong_df[['wildlife_corridor', 'road_count', 'speed_limit', 'white_road_grade', 'pig_count', 'rani_count']].values
y_hong = yes_hong_df['rk_012'].values

In [ ]:
df['total_rk'].value_counts()

total_rk
0     617
1      82
2      31
3      19
4       9
5       9
6       4
8       3
10      3
7       3
9       2
13      1
14      1
Name: count, dtype: int64

# Classifier

## KNN

In [ ]:
knn = KNeighborsClassifier()

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
knn_train_pred = knn.predict(X_train)
knn_test_pred = knn.predict(X_test)

In [ ]:
confusion_matrix(y_train, knn_train_pred)

array([[426,   0,   0],
       [  0,  82,   7],
       [  0,  14,  11]])

In [ ]:
print('train f1_score: ', f1_score(y_train, knn_train_pred, average=None))
print('test f1_score', f1_score(y_test, knn_test_pred, average=None))

train f1_score:  [1.         0.88648649 0.51162791]
test f1_score [1.         0.83333333 0.2       ]


In [ ]:
print('train acc: ', knn.score(X_train, y_train))
print('test acc: ', knn.score(X_test, y_test))

train acc:  0.9611111111111111
test acc:  0.9407407407407408


## Log

In [ ]:
log = LogisticRegression()

In [ ]:
log.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
log_train_pred = log.predict(X_train)
log_test_pred = log.predict(X_test)

In [ ]:
print('train r2_score: ', r2_score(y_train, log_train_pred))
print('test r2_score: ', r2_score(y_test, log_test_pred))

train r2_score:  0.8564159586168554
test r2_score:  0.900990099009901


In [ ]:
print('train acc: ', log.score(X_train, y_train))
print('test acc: ', log.score(X_test, y_test))

train acc:  0.9592592592592593
test acc:  0.9703703703703703


## Decision Tree Classifier

In [ ]:
tree = DecisionTreeClassifier(max_depth=5)

In [ ]:
tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5)

In [ ]:
tree_train_pred = tree.predict(X_train)
tree_test_pred = tree.predict(X_test)

In [ ]:
print('train r2_score: ', r2_score(y_train, tree_train_pred))
print('test r2_score: ', r2_score(y_test, tree_test_pred))

train r2_score:  0.9282079793084277
test r2_score:  0.8514851485148516


In [ ]:
print('train acc: ', tree.score(X_train, y_train))
print('test acc: ', tree.score(X_test, y_test))

train acc:  0.9796296296296296
test acc:  0.9555555555555556


## SVM

In [ ]:
svm = SVC(probability=True)

In [ ]:
svm.fit(X_train, y_train)

SVC(probability=True)

In [ ]:
svm_train_pred = svm.predict(X_train)
svm_test_pred = svm.predict(X_test)

In [ ]:
print('train r2_score: ', r2_score(y_train, svm_train_pred))
print('test r2_score: ', r2_score(y_test, svm_test_pred))

train r2_score:  0.8042035799320756
test r2_score:  0.8267326732673268


In [ ]:
print('train acc: ', svm.score(X_train, y_train))
print('test acc: ', svm.score(X_test, y_test))

train acc:  0.95
test acc:  0.9481481481481482


## SGD

In [ ]:
sgd = SGDClassifier(loss='log_loss')

In [ ]:
sgd.fit(X_train, y_train)

SGDClassifier(loss='log_loss')

In [ ]:
sgd_train_pred = sgd.predict(X_train)
sgd_test_pred = sgd.predict(X_test)

In [ ]:
print('train acc: ', sgd.score(X_train, y_train))
print('test acc: ', sgd.score(X_test, y_test))

train acc:  0.9462962962962963
test acc:  0.9407407407407408


# 앙상블

## XXX Voting

In [ ]:
vote = VotingClassifier(estimators=[('knn', knn),
                                    ('tree', tree),
                                    ('logistic', log),
                                    ('sgd', sgd),
                                    ('svm', svm)],
                        voting='soft',
                        n_jobs=-1)

In [ ]:
vote.fit(X_train, y_train)

VotingClassifier(estimators=[('knn', KNeighborsClassifier()),
                             ('tree', DecisionTreeClassifier(max_depth=5)),
                             ('logistic', LogisticRegression()),
                             ('sgd', SGDClassifier(loss='log_loss')),
                             ('svm', SVC(probability=True))],
                 n_jobs=-1, voting='soft')

In [ ]:
print(vote.score(X_train, y_train))
print(vote.score(X_test, y_test))

0.9740740740740741
0.9703703703703703


In [ ]:
cv_vote = cross_validate(estimator=vote, X= X_train, y=y_train,
                         return_train_score=True, n_jobs=-1)

In [ ]:
cv_vote

{'fit_time': array([0.16083789, 0.1542449 , 0.10201168, 0.11504102, 0.07734323]),
 'score_time': array([0.01179361, 0.01597261, 0.02052808, 0.00616503, 0.00780129]),
 'test_score': array([0.9537037 , 0.9537037 , 0.94444444, 0.96296296, 0.78703704]),
 'train_score': array([0.95833333, 0.96527778, 0.96296296, 0.95601852, 0.78935185])}

In [ ]:
vote_hong_pred = vote.predict(X_hong)
confusion_matrix(y_hong, vote_hong_pred)

array([[85,  0,  0],
       [ 1, 16,  4],
       [ 0,  3,  0]])

## XXX Random Forest

In [ ]:
forest = RandomForestClassifier(max_depth=7, n_jobs=-1)

In [ ]:
forest.fit(X_train, y_train)

RandomForestClassifier(max_depth=7, n_jobs=-1)

In [ ]:
cv_forest = cross_validate(estimator=forest, X=X_train, y=y_train,
                    return_train_score=True, n_jobs=-1, cv=7)

In [ ]:
cv_forest

{'fit_time': array([0.5434823 , 0.62719703, 0.47413325, 0.53706765, 0.48914599,
        0.5139854 , 0.40287638]),
 'score_time': array([0.05449295, 0.05603218, 0.05134153, 0.05243325, 0.04971361,
        0.04034019, 0.03612375]),
 'test_score': array([0.94871795, 0.92207792, 0.96103896, 0.96103896, 0.93506494,
        0.96103896, 0.94805195]),
 'train_score': array([0.98917749, 0.99568035, 0.99352052, 0.98920086, 0.99352052,
        0.98920086, 0.99568035])}

In [ ]:
forest_hong_pred = forest.predict(X_hong)
confusion_matrix(y_hong, forest_hong_pred)

array([[85,  0,  0],
       [ 1, 17,  3],
       [ 0,  2,  1]])

In [ ]:
forest_hong_pred

array([0, 1, 2, 0, 1, 2, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Randomizedcv

In [ ]:
params = {'n_estimators': scipy.stats.randint(100, 151),
          'max_depth': scipy.stats.randint(3, 8),
          'min_samples_split': scipy.stats.randint(2, 50),
          'min_samples_leaf': scipy.stats.randint(2, 50),
          'min_impurity_decrease': scipy.stats.uniform(0.0001, 0.001)}

In [ ]:
rand_cv = RandomizedSearchCV(estimator=forest,
                             param_distributions=params,    # 파라미터들의 확률 분포
                             n_iter=100,                    # 파라미터들의 조합 갯수
                             n_jobs=-1)

In [ ]:
rand_cv.fit(X, y)

RandomizedSearchCV(estimator=RandomForestClassifier(max_depth=7, n_jobs=-1),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7c6e3e614790>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x7c6e3e56fd50>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7c6e3e56c190>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7c6e3e56f9d0>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7c6e3e5e95d0>})

In [ ]:
rand_cv.best_params_

{'max_depth': 6,
 'min_impurity_decrease': np.float64(0.0007524150843491184),
 'min_samples_leaf': 7,
 'min_samples_split': 16,
 'n_estimators': 107}

In [ ]:
rand_cv.best_score_

np.float64(0.9525925925925925)

In [ ]:
best_forest = rand_cv.best_estimator_

In [ ]:
bestfor_pre = best_forest.predict(X_hong)

In [ ]:
confusion_matrix(y_hong, bestfor_pre)

array([[85,  0,  0],
       [ 1, 20,  0],
       [ 0,  3,  0]])

## XXX Bagging

In [ ]:
bagging = BaggingClassifier(estimator=DecisionTreeClassifier(),
                            n_estimators=50,
                            oob_score=True, # out of bagging -> 훈련에 한 번도 뽑히지 않은 세트 -> 검증 세트로 사용.
                            n_jobs=-1)

In [ ]:
bagging.fit(X_train, y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=50,
                  n_jobs=-1, oob_score=True)

In [ ]:
cv_bagging = cross_validate(estimator=bagging, X=X_train, y=y_train,
                    return_train_score=True, n_jobs=-1, cv=10)

In [ ]:
cv_bagging

{'fit_time': array([0.23576498, 0.23821235, 0.21616101, 0.2370801 , 0.23409367,
        0.22463179, 0.2238462 , 0.22101521, 0.30309868, 0.3073895 ]),
 'score_time': array([0.0243423 , 0.02946591, 0.02422547, 0.02534413, 0.02391672,
        0.03166795, 0.02596855, 0.03023863, 0.03293657, 0.03813291]),
 'test_score': array([0.98148148, 0.94444444, 0.92592593, 0.96296296, 0.96296296,
        0.94444444, 1.        , 0.92592593, 0.96296296, 0.94444444]),
 'train_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])}

## 이거이거이거 GradientBoosting

In [ ]:
gb_clf = GradientBoostingClassifier()

In [ ]:
gb_clf.fit(X, y)

GradientBoostingClassifier()

In [ ]:
gb_clf.score(X_hong, y_hong)

0.9357798165137615

In [ ]:
gb_pred_hong = gb_clf.predict(X_hong)

In [ ]:
confusion_matrix(y_hong, gb_pred_hong)

array([[85,  0,  0],
       [ 0, 16,  5],
       [ 0,  2,  1]])

### Randomizedcv

In [ ]:
params = {'max_depth': scipy.stats.randint(3, 8),
          'n_estimators': scipy.stats.randint(50, 151),
          'min_samples_split': scipy.stats.randint(2, 50),
          'min_samples_leaf': scipy.stats.randint(2, 50),
          'min_impurity_decrease': scipy.stats.uniform(0.0001, 0.001)}

In [ ]:
rand_cv = RandomizedSearchCV(estimator=gb_clf,
                             param_distributions=params,    # 파라미터들의 확률 분포
                             n_iter=1000,                   # 파라미터들의 조합 갯수
                             n_jobs=-1)

In [ ]:
rand_cv.fit(X, y)

RandomizedSearchCV(estimator=GradientBoostingClassifier(), n_iter=1000,
                   n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7c6e3e5c3790>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x7c6e3e56f8d0>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7c6e3c4ef6d0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7c6e3c4ef790>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7c6e3c4edd10>})

In [ ]:
rand_cv.best_params_

{'max_depth': 3,
 'min_impurity_decrease': np.float64(0.00015463453073005708),
 'min_samples_leaf': 12,
 'min_samples_split': 35,
 'n_estimators': 131}

In [ ]:
rand_cv.best_score_

np.float64(0.9585185185185185)

In [ ]:
best_gb = rand_cv.best_estimator_

In [ ]:
best_gb_pre = best_gb.predict(X)
confusion_matrix(y, best_gb_pre)

array([[532,   0,   0],
       [  0, 111,   0],
       [  0,   0,  32]])

In [ ]:
best_gb_hong_pre = best_gb.predict(X_hong)
confusion_matrix(y_hong, best_gb_hong_pre)

array([[85,  0,  0],
       [ 0, 15,  6],
       [ 0,  2,  1]])

### 예측값들 DataFrame 생성

In [ ]:
hong_pred_df = pd.DataFrame()

In [ ]:
hongchun_grid

array(['grid_748', 'grid_846', 'grid_814', 'grid_459', 'grid_396',
       'grid_460', 'grid_491', 'grid_524', 'grid_588', 'grid_492',
       'grid_556', 'grid_493', 'grid_525', 'grid_589', 'grid_364',
       'grid_428', 'grid_429', 'grid_461', 'grid_397', 'grid_365',
       'grid_430', 'grid_366', 'grid_398', 'grid_462', 'grid_557',
       'grid_526', 'grid_494', 'grid_558', 'grid_590', 'grid_527',
       'grid_559', 'grid_591', 'grid_592', 'grid_528', 'grid_333',
       'grid_301', 'grid_269', 'grid_302', 'grid_334', 'grid_303',
       'grid_431', 'grid_495', 'grid_463', 'grid_399', 'grid_464',
       'grid_496', 'grid_620', 'grid_685', 'grid_653', 'grid_621',
       'grid_686', 'grid_654', 'grid_622', 'grid_687', 'grid_623',
       'grid_716', 'grid_717', 'grid_749', 'grid_750', 'grid_718',
       'grid_782', 'grid_783', 'grid_751', 'grid_878', 'grid_815',
       'grid_911', 'grid_879', 'grid_847', 'grid_848', 'grid_880',
       'grid_912', 'grid_913', 'grid_849', 'grid_655', 'grid_7

In [ ]:
hong_pred_df['grid_id'] = hongchun_grid

In [ ]:
best_gb_hong_pre

array([0, 1, 2, 0, 2, 2, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 2,
       0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
hong_pred_df['pred_012'] = best_gb_hong_pre

In [ ]:
best_gb_hong_pre == y_hong

array([ True,  True, False,  True, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
hong_pred_df['pred_TF'] = best_gb_hong_pre == y_hong

In [ ]:
hong_pred_df.to_excel('/content/drive/MyDrive/중간 프로젝트/Colaboratories/hong_pred_df.xlsx')

In [ ]:
#
hong_pred_df[(hong_pred_df['pred_012'] == 2) & (hong_pred_df['pred_TF'] == True)]

grid_id  pred_012  pred_TF
27  grid_558         2     True

In [ ]:
hong_pred_df[(hong_pred_df['pred_012'] == 2) & (hong_pred_df['pred_TF'] == False)]

grid_id  pred_012  pred_TF
2   grid_814         2    False
4   grid_396         2    False
5   grid_460         2    False
21  grid_366         2    False
34  grid_333         2    False
83  grid_816         2    False

# GradientBoosting -> MinMax PrePro

In [ ]:
no_hong_df = no_hong_df[['wildlife_corridor', 'road_count', 'speed_limit', 'white_road_grade', 'pig_count', 'rani_count', 'dist_to_eco_m']]
yes_hong_df = yes_hong_df[['wildlife_corridor', 'road_count', 'speed_limit', 'white_road_grade', 'pig_count', 'rani_count', 'dist_to_eco_m']]

In [ ]:
mm = MinMaxScaler()

no_hong_df_mm = pd.DataFrame(mm.fit_transform(no_hong_df), columns=no_hong_df.columns)
yes_hong_df_mm = pd.DataFrame(mm.fit_transform(yes_hong_df), columns=yes_hong_df.columns)

In [ ]:
X_no_hong_df_mm = no_hong_df_mm[['wildlife_corridor', 'road_count', 'speed_limit', 'white_road_grade', 'pig_count', 'rani_count', 'dist_to_eco_m']].values
X_yes_hong_df_mm = yes_hong_df_mm[['wildlife_corridor', 'road_count', 'speed_limit', 'white_road_grade', 'pig_count', 'rani_count', 'dist_to_eco_m']].values

In [ ]:
gb_clf2 = GradientBoostingClassifier()

In [ ]:
params = {'max_depth': scipy.stats.randint(3, 8),
          'n_estimators': scipy.stats.randint(50, 151),
          'min_samples_split': scipy.stats.randint(2, 50),
          'min_samples_leaf': scipy.stats.randint(2, 50),
          'min_impurity_decrease': scipy.stats.uniform(0.0001, 0.001)}

rand_cv2 = RandomizedSearchCV(estimator=gb_clf2,
                             param_distributions=params,    # 파라미터들의 확률 분포
                             n_iter=1000,                   # 파라미터들의 조합 갯수
                             n_jobs=-1)

In [ ]:
rand_cv2.fit(X_no_hong_df_mm, y)

RandomizedSearchCV(estimator=GradientBoostingClassifier(), n_iter=1000,
                   n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7c6e3c26b2d0>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x7c6e3e62d350>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7c6e3e62d5d0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7c6e3e62c690>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7c6e3e62e790>})

In [ ]:
best_gb2 = rand_cv2.best_estimator_

In [ ]:
best_gb_pre2 = best_gb2.predict(X_no_hong_df_mm)
confusion_matrix(y, best_gb_pre2)

array([[532,   0,   0],
       [  0, 111,   0],
       [  0,   1,  31]])

In [ ]:
best_gb_hong_pre = best_gb.predict(X_hong)
confusion_matrix(y_hong, best_gb_hong_pre)

array([[85,  0,  0],
       [ 0, 15,  6],
       [ 0,  2,  1]])

In [ ]:
hong_mm_pred_df = pd.DataFrame()

In [ ]:
hong_mm_pred_df['grid_id'] = hongchun_grid

In [ ]:
hong_mm_pred_df['pred_012'] = best_gb_hong_pre

In [ ]:
hong_mm_pred_df['pred_TF'] = best_gb_hong_pre == y_hong

In [ ]:
hong_mm_pred_df[(hong_mm_pred_df['pred_012'] == 2) & (hong_mm_pred_df['pred_TF'] == True)]

grid_id  pred_012  pred_TF
27  grid_558         2     True

In [ ]:
hong_mm_pred_df[(hong_mm_pred_df['pred_012'] == 2) & (hong_mm_pred_df['pred_TF'] == False)]

grid_id  pred_012  pred_TF
2   grid_814         2    False
4   grid_396         2    False
5   grid_460         2    False
21  grid_366         2    False
34  grid_333         2    False
83  grid_816         2    False

# <정리>

~~~
모델링은 RandomForest 사용.

찐 테스트세트의 X로 예측한 값 중 2로 나온 값이 우리가 생태 통로를 지어야할 곳.
-> 2로 나온 데이터가 어떤 그리드인지 파악.

만약 2로 나온 그리드가 생태 통로가 많다면,
(1) 생태 통로를 보수
(2) 생태 통로를 추가 설치

찐찐 테스트세트(yes 홍천)의 y 값은 오픈 x.

gridsearch로 최적의 파라미터 찾기.
~~~

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/중간 프로젝트/코랩으로 옮길 엑셀들/DF_final_final.xlsx')

In [ ]:
hongchun = df[df['grid_id'].isin(hongchun_grid)]

In [ ]:
sum(hongchun['total_rk'])

48

In [ ]:
no_hongchun = df[~df['grid_id'].isin(hongchun_grid)]

In [ ]:
sum(no_hongchun['total_rk'])

378